#!/usr/bin/env python3
"""Librarian — Artifact management for agent knowledge.

Manages markdown files with YAML frontmatter in structured directories.
Maintains an index.md file tracking all knowledge artifacts.
Researches are organized as YYYY_MM_DD__topic directories.

All commands output JSON for easy parsing by agents.

Usage:
    python librarian.py init [--scope project|global] [--categories cat1,cat2,...]
    python librarian.py write <category> <slug> [--title TITLE] [--content CONTENT] [--file FILE] [--tags t1,t2] [--scope project|global]
    python librarian.py read <category> <slug> [--scope project|global]
    python librarian.py list [--category CATEGORY] [--scope project|global] [--tags t1,t2]
    python librarian.py search <query> [--category CATEGORY] [--scope project|global] [--field title|content|tags|all]
    python librarian.py fetch <partial> [--scope project|global]
    python librarian.py move <category> <slug> <new-category> [--scope project|global]
    python librarian.py delete <category> <slug> [--scope project|global]
    python librarian.py index [--scope project|global] [--rebuild]

Scope:
    project  — ./docs/  (relative to current working directory)
    global   — $AGENT_ROOT/docs/ or ~/.agents/docs/
"""

import argparse
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DEFAULT_CATEGORIES = ["researches", "specs", "tasks", "docs"]

FRONTMATTER_TEMPLATE = """\
---
title: {title}
category: {category}
slug: {slug}
created: {created}
updated: {updated}
tags: {tags}
scope: {scope}
---

"""

INDEX_HEADER = """\
# Knowledge Index

> Auto-generated by librarian. Do not edit manually — use `python scripts/librarian.py index --rebuild` to regenerate.

"""

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _slugify(text: str) -> str:
    """Convert text to a URL-friendly slug: lowercase, hyphens, max 60 chars."""
    text = text.lower().strip()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_]+", "-", text)
    text = re.sub(r"-+", "-", text)
    text = text.strip("-")
    return text[:60]


def _get_base_dir(scope: str) -> Path:
    """Return the base docs directory for the given scope."""
    if scope == "global":
        agent_root = os.environ.get("AGENT_ROOT", os.path.expanduser("~/.agents"))
        return Path(agent_root) / "docs"
    return Path.cwd() / "docs"


def _parse_frontmatter(content: str) -> Tuple[Dict[str, str], str]:
    """Parse YAML frontmatter from markdown content.

    Returns (metadata_dict, body_content).
    Handles simple key: value pairs. Lists are stored as raw strings.
    """
    if not content.startswith("---"):
        return {}, content

    end = content.find("---", 3)
    if end == -1:
        return {}, content

    fm_text = content[3:end].strip()
    body = content[end + 3:].strip()

    meta: Dict[str, str] = {}
    for line in fm_text.splitlines():
        line = line.strip()
        if ":" in line:
            key, _, value = line.partition(":")
            meta[key.strip()] = value.strip()

    return meta, body


def _build_frontmatter(
    title: str,
    category: str,
    slug: str,
    created: str,
    updated: str,
    tags: List[str],
    scope: str,
) -> str:
    """Build frontmatter string."""
    tags_str = "[" + ", ".join(f'"{t}"' for t in tags) + "]"
    return FRONTMATTER_TEMPLATE.format(
        title=title,
        category=category,
        slug=slug,
        created=created,
        updated=updated,
        tags=tags_str,
        scope=scope,
    )


def _now_iso() -> str:
    """Return current UTC time as ISO 8601 string."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _today_prefix() -> str:
    """Return today's date as YYYY_MM_DD prefix for researches directories."""
    return datetime.now(timezone.utc).strftime("%Y_%m_%d")


def _output(data: dict) -> None:
    """Print JSON to stdout."""
    print(json.dumps(data, indent=2, ensure_ascii=False))


def _error(msg: str) -> None:
    """Print error JSON to stdout and exit."""
    _output({"error": msg})
    sys.exit(1)


def _artifact_path(base: Path, category: str, slug: str, artifact_type: Optional[str] = None) -> Path:
    """Return the file path for an artifact.

    For 'researches' category, uses date-prefixed directory structure:
        researches/YYYY_MM_DD__slug/index.md
    For 'specs' category with artifact_type, uses date-prefixed directory:
        specs/YYYY_MM_DD__slug/solution.md (for solution-architect)
        specs/YYYY_MM_DD__slug/technical.md (for technical-architect)
    For all other categories, uses flat structure:
        category/slug.md
    """
    if category == "researches":
        # Find existing date-prefixed directory for this slug
        researches_dir = base / "researches"
        if researches_dir.is_dir():
            for entry in sorted(researches_dir.iterdir()):
                if entry.is_dir() and entry.name.endswith(f"__{slug}"):
                    return entry / "index.md"
        # New artifact: create date-prefixed directory
        date_prefix = _today_prefix()
        return base / "researches" / f"{date_prefix}__{slug}" / "index.md"
    
    if category == "specs" and artifact_type:
        # Find existing date-prefixed directory for this slug
        specs_dir = base / "specs"
        if specs_dir.is_dir():
            for entry in sorted(specs_dir.iterdir()):
                if entry.is_dir() and entry.name.endswith(f"__{slug}"):
                    return entry / f"{artifact_type}.md"
        # New artifact: create date-prefixed directory
        date_prefix = _today_prefix()
        return base / "specs" / f"{date_prefix}__{slug}" / f"{artifact_type}.md"
    
    return base / category / f"{slug}.md"


def _find_slug_in_category(base: Path, category: str, slug: str, artifact_type: Optional[str] = None) -> Optional[Path]:
    """Find an artifact by slug in a category with date-prefixed directories."""
    cat_dir = base / category
    if not cat_dir.is_dir():
        return None
    for entry in sorted(cat_dir.iterdir()):
        if entry.is_dir() and entry.name.endswith(f"__{slug}"):
            if artifact_type:
                artifact_file = entry / f"{artifact_type}.md"
            else:
                artifact_file = entry / "index.md"
            if artifact_file.exists():
                return artifact_file
    return None


def _read_artifact(filepath: Path) -> Optional[Tuple[Dict[str, str], str]]:
    """Read and parse an artifact file. Returns (meta, body) or None."""
    if not filepath.exists():
        return None
    content = filepath.read_text(encoding="utf-8")
    return _parse_frontmatter(content)


def _collect_artifacts(
    base: Path, category: Optional[str] = None
) -> List[Tuple[Path, Dict[str, str], str]]:
    """Walk the docs directory and collect all artifacts.

    Returns list of (filepath, meta, body).
    """
    results: List[Tuple[Path, Dict[str, str], str]] = []

    if category:
        cat_dir = base / category
        if not cat_dir.is_dir():
            return results
        search_dirs = [cat_dir]
    else:
        if not base.is_dir():
            return results
        search_dirs = sorted(base.iterdir())

    for cat_dir in search_dirs:
        if not cat_dir.is_dir():
            continue
        cat_name = cat_dir.name

        if cat_name == "researches":
            # Date-prefixed subdirectories
            for entry in sorted(cat_dir.iterdir()):
                if entry.is_dir():
                    index_file = entry / "index.md"
                    if index_file.exists():
                        parsed = _read_artifact(index_file)
                        if parsed:
                            meta, body = parsed
                            results.append((index_file, meta, body))
        elif cat_name == "specs":
            # Mixed: date-prefixed subdirectories and flat .md files
            for entry in sorted(cat_dir.iterdir()):
                if entry.is_dir():
                    # Date-prefixed directory with solution.md or technical.md
                    for md_file in sorted(entry.glob("*.md")):
                        parsed = _read_artifact(md_file)
                        if parsed:
                            meta, body = parsed
                            results.append((md_file, meta, body))
                elif entry.suffix == ".md":
                    # Flat .md files
                    parsed = _read_artifact(entry)
                    if parsed:
                        meta, body = parsed
                        results.append((entry, meta, body))
        else:
            # Flat .md files
            for md_file in sorted(cat_dir.glob("*.md")):
                parsed = _read_artifact(md_file)
                if parsed:
                    meta, body = parsed
                    results.append((md_file, meta, body))

    return results


def _rebuild_index(base: Path) -> None:
    """Rebuild the index.md file from all artifacts."""
    artifacts = _collect_artifacts(base)

    # Group by category
    by_category: Dict[str, List[Tuple[Path, Dict[str, str], str]]] = {}
    for filepath, meta, body in artifacts:
        cat = meta.get("category", filepath.parent.parent.name if filepath.name == "index.md" else filepath.parent.name)
        if cat not in by_category:
            by_category[cat] = []
        by_category[cat].append((filepath, meta, body))

    # Build index content
    lines = [INDEX_HEADER]

    for cat in sorted(by_category.keys()):
        cat_artifacts = by_category[cat]
        # Category heading
        lines.append(f"## {cat.title()}\n")

        for filepath, meta, body in sorted(cat_artifacts, key=lambda x: x[1].get("updated", x[1].get("created", "")), reverse=True):
            title = meta.get("title", filepath.stem)
            slug = meta.get("slug", filepath.stem)
            tags_raw = meta.get("tags", "[]")
            try:
                tags = json.loads(tags_raw)
            except (json.JSONDecodeError, TypeError):
                tags = []
            created = meta.get("created", "")
            updated = meta.get("updated", "")

            # Relative path from docs root
            rel_path = filepath.relative_to(base)
            tag_str = " ".join(f"`{t}`" for t in tags) if tags else ""
            date_str = updated[:10] if updated else (created[:10] if created else "")

            lines.append(f"- [{title}]({rel_path}) — {date_str} {tag_str}")

        lines.append("")

    index_path = base / "index.md"
    index_path.write_text("\n".join(lines), encoding="utf-8")


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------


def cmd_init(args: argparse.Namespace) -> None:
    """Initialize the directory structure."""
    base = _get_base_dir(args.scope)
    categories = args.categories.split(",") if args.categories else DEFAULT_CATEGORIES
    created = []

    for cat in categories:
        cat = cat.strip()
        cat_dir = base / cat
        cat_dir.mkdir(parents=True, exist_ok=True)
        created.append(str(cat_dir))

    # Create initial index
    _rebuild_index(base)

    _output({
        "action": "init",
        "scope": args.scope,
        "base": str(base),
        "directories": created,
        "index": str(base / "index.md"),
    })


def cmd_write(args: argparse.Namespace) -> None:
    """Write or update an artifact."""
    base = _get_base_dir(args.scope)
    slug = _slugify(args.slug) if args.slug else _slugify(args.title or "untitled")
    category = args.category
    title = args.title or slug.replace("-", " ").title()

    # Ensure category directory exists
    cat_dir = base / category
    cat_dir.mkdir(parents=True, exist_ok=True)

    artifact_type = getattr(args, 'artifact_type', None)
    filepath = _artifact_path(base, category, slug, artifact_type)

    # Get content
    if args.file:
        content = Path(args.file).read_text(encoding="utf-8")
    elif args.content:
        content = args.content
    elif not sys.stdin.isatty():
        content = sys.stdin.read()
    else:
        content = ""

    # Handle existing artifact (preserve created date)
    now = _now_iso()
    existing = _read_artifact(filepath)
    if existing:
        created = existing[0].get("created", now)
        # If no new content provided and file exists, just update metadata
        if not args.content and not args.file and sys.stdin.isatty():
            # Preserve existing body
            content = existing[1]
    else:
        created = now

    # Merge tags
    tags = args.tags.split(",") if args.tags else []
    if existing and not args.tags:
        # Preserve existing tags if none specified
        existing_tags = existing[0].get("tags", "[]")
        try:
            tags = json.loads(existing_tags)
        except (json.JSONDecodeError, TypeError):
            tags = []

    frontmatter = _build_frontmatter(
        title=title, category=category, slug=slug,
        created=created, updated=now, tags=tags, scope=args.scope,
    )

    full_content = frontmatter + content

    # Ensure parent directory exists (for researches date-prefixed dirs)
    filepath.parent.mkdir(parents=True, exist_ok=True)
    filepath.write_text(full_content, encoding="utf-8")

    # Rebuild index
    _rebuild_index(base)

    _output({
        "action": "write",
        "path": str(filepath),
        "slug": slug,
        "category": category,
        "title": title,
        "scope": args.scope,
        "created": created,
        "updated": now,
        "tags": tags,
    })


def cmd_read(args: argparse.Namespace) -> None:
    """Read an artifact."""
    base = _get_base_dir(args.scope)
    slug = args.slug
    category = args.category

    artifact_type = getattr(args, 'artifact_type', None)
    filepath = _artifact_path(base, category, slug, artifact_type)
    parsed = _read_artifact(filepath)

    if not parsed:
        _error(f"Artifact not found: {category}/{slug}")

    meta, body = parsed
    _output({
        "action": "read",
        "path": str(filepath),
        "slug": slug,
        "category": category,
        "scope": args.scope,
        "meta": meta,
        "body": body,
    })


def cmd_list(args: argparse.Namespace) -> None:
    """List artifacts, optionally filtered by category and tags."""
    base = _get_base_dir(args.scope)
    artifacts = _collect_artifacts(base, category=args.category)

    # Filter by tags if specified
    filter_tags = args.tags.split(",") if args.tags else None
    results = []

    for filepath, meta, body in artifacts:
        if filter_tags:
            try:
                artifact_tags = json.loads(meta.get("tags", "[]"))
            except (json.JSONDecodeError, TypeError):
                artifact_tags = []
            if not any(t in artifact_tags for t in filter_tags):
                continue

        results.append({
            "slug": meta.get("slug", filepath.stem),
            "title": meta.get("title", filepath.stem),
            "category": meta.get("category", filepath.parent.name),
            "created": meta.get("created", ""),
            "updated": meta.get("updated", ""),
            "tags": meta.get("tags", "[]"),
            "path": str(filepath),
        })

    _output({
        "action": "list",
        "scope": args.scope,
        "category": args.category or "all",
        "count": len(results),
        "artifacts": results,
    })


def cmd_search(args: argparse.Namespace) -> None:
    """Full-text search across artifacts."""
    base = _get_base_dir(args.scope)
    query = args.query.lower()
    field = args.field or "all"
    artifacts = _collect_artifacts(base, category=args.category)

    results = []
    for filepath, meta, body in artifacts:
        score = 0.0
        matches = []

        # Search in title
        if field in ("all", "title"):
            title = meta.get("title", "").lower()
            if query in title:
                score += 2.0
                matches.append("title")

        # Search in tags
        if field in ("all", "tags"):
            try:
                tags = json.loads(meta.get("tags", "[]"))
            except (json.JSONDecodeError, TypeError):
                tags = []
            if any(query in t.lower() for t in tags):
                score += 1.5
                matches.append("tags")

        # Search in content
        if field in ("all", "content"):
            if query in body.lower():
                # Count occurrences for relevance
                count = body.lower().count(query)
                score += min(count * 0.1, 1.0)
                matches.append("content")

        # Search in category/slug
        if field == "all":
            if query in meta.get("category", "").lower():
                score += 0.5
                matches.append("category")
            if query in meta.get("slug", "").lower():
                score += 0.5
                matches.append("slug")

        if score > 0:
            results.append({
                "slug": meta.get("slug", filepath.stem),
                "title": meta.get("title", filepath.stem),
                "category": meta.get("category", filepath.parent.name),
                "score": round(score, 2),
                "matched_in": matches,
                "path": str(filepath),
            })

    # Sort by score descending
    results.sort(key=lambda r: r["score"], reverse=True)

    _output({
        "action": "search",
        "query": args.query,
        "scope": args.scope,
        "category": args.category or "all",
        "field": field,
        "count": len(results),
        "results": results,
    })


def cmd_fetch(args: argparse.Namespace) -> None:
    """Find an artifact by partial slug or title match."""
    base = _get_base_dir(args.scope)
    partial = args.partial.lower()
    artifacts = _collect_artifacts(base)

    # Score matches
    candidates = []
    for filepath, meta, body in artifacts:
        slug = meta.get("slug", filepath.stem).lower()
        title = meta.get("title", "").lower()
        score = 0.0

        if slug == partial:
            score = 3.0  # Exact slug match
        elif slug.startswith(partial):
            score = 2.0  # Slug prefix match
        elif partial in slug:
            score = 1.5  # Slug contains
        elif title == partial:
            score = 2.5  # Exact title match
        elif partial in title:
            score = 1.0  # Title contains

        if score > 0:
            candidates.append({
                "slug": meta.get("slug", filepath.stem),
                "title": meta.get("title", filepath.stem),
                "category": meta.get("category", filepath.parent.name),
                "score": score,
                "path": str(filepath),
            })

    candidates.sort(key=lambda c: c["score"], reverse=True)

    _output({
        "action": "fetch",
        "partial": args.partial,
        "scope": args.scope,
        "count": len(candidates),
        "results": candidates[:10],  # Limit to top 10
    })


def cmd_move(args: argparse.Namespace) -> None:
    """Move an artifact to a different category."""
    base = _get_base_dir(args.scope)
    slug = args.slug
    old_category = args.category
    new_category = args.new_category
    artifact_type = getattr(args, 'artifact_type', None)

    old_path = _artifact_path(base, old_category, slug, artifact_type)
    parsed = _read_artifact(old_path)
    if not parsed:
        _error(f"Artifact not found: {old_category}/{slug}")

    meta, body = parsed

    # Ensure new category directory exists
    new_cat_dir = base / new_category
    new_cat_dir.mkdir(parents=True, exist_ok=True)

    new_path = _artifact_path(base, new_category, slug, artifact_type)

    # Update frontmatter
    now = _now_iso()
    try:
        tags = json.loads(meta.get("tags", "[]"))
    except (json.JSONDecodeError, TypeError):
        tags = []

    frontmatter = _build_frontmatter(
        title=meta.get("title", slug.replace("-", " ").title()),
        category=new_category,
        slug=slug,
        created=meta.get("created", now),
        updated=now,
        tags=tags,
        scope=args.scope,
    )

    # Ensure parent directory exists (for researches date-prefixed dirs)
    new_path.parent.mkdir(parents=True, exist_ok=True)
    new_path.write_text(frontmatter + body, encoding="utf-8")

    # Remove old file and empty parent dir if it was a researches date-dir
    old_path.unlink()
    if old_category == "researches" and old_path.parent != base / "researches":
        # Try to remove the date-prefixed directory if empty
        try:
            old_path.parent.rmdir()
        except OSError:
            pass  # Directory not empty, leave it

    # Rebuild index
    _rebuild_index(base)

    _output({
        "action": "move",
        "slug": slug,
        "from": old_category,
        "to": new_category,
        "old_path": str(old_path),
        "new_path": str(new_path),
        "scope": args.scope,
    })


def cmd_delete(args: argparse.Namespace) -> None:
    """Delete an artifact."""
    base = _get_base_dir(args.scope)
    slug = args.slug
    category = args.category
    artifact_type = getattr(args, 'artifact_type', None)

    filepath = _artifact_path(base, category, slug, artifact_type)
    if not filepath.exists():
        _error(f"Artifact not found: {category}/{slug}")

    filepath.unlink()

    # Clean up empty date-prefixed directory for researches
    if category == "researches" and filepath.parent != base / "researches":
        try:
            filepath.parent.rmdir()
        except OSError:
            pass  # Directory not empty, leave it
    
    # Clean up empty date-prefixed directory for specs
    if category == "specs" and artifact_type and filepath.parent != base / "specs":
        try:
            filepath.parent.rmdir()
        except OSError:
            pass  # Directory not empty, leave it

    # Rebuild index
    _rebuild_index(base)

    _output({
        "action": "delete",
        "slug": slug,
        "category": category,
        "path": str(filepath),
        "scope": args.scope,
    })


def cmd_index(args: argparse.Namespace) -> None:
    """Rebuild and display the knowledge index."""
    base = _get_base_dir(args.scope)

    if args.rebuild:
        _rebuild_index(base)

    index_path = base / "index.md"
    if not index_path.exists():
        _error("Index not found. Run with --rebuild to create it.")

    content = index_path.read_text(encoding="utf-8")
    _output({
        "action": "index",
        "scope": args.scope,
        "path": str(index_path),
        "content": content,
    })


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Librarian — Artifact management for agent knowledge",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    subparsers = parser.add_subparsers(dest="command", help="Command to run")

    # Common arguments
    def _add_scope(p: argparse.ArgumentParser) -> None:
        p.add_argument("--scope", choices=["project", "global"], default="project",
                       help="Scope: project (./docs/) or global ($AGENT_ROOT/docs/)")

    # init
    p_init = subparsers.add_parser("init", help="Initialize directory structure")
    _add_scope(p_init)
    p_init.add_argument("--categories", default=None,
                        help="Comma-separated categories (default: researches,specs,tasks,docs)")

    # write
    p_write = subparsers.add_parser("write", help="Write or update an artifact")
    p_write.add_argument("category", help="Category (e.g., researches, specs, tasks)")
    p_write.add_argument("slug", help="Slug for the artifact (auto-slugified)")
    p_write.add_argument("--title", help="Title (defaults to slugified title)")
    p_write.add_argument("--content", help="Content string")
    p_write.add_argument("--file", help="Read content from file")
    p_write.add_argument("--tags", help="Comma-separated tags")
    p_write.add_argument("--artifact-type", dest="artifact_type", default=None,
                         help="Artifact type for specs category (solution, technical)")
    _add_scope(p_write)

    # read
    p_read = subparsers.add_parser("read", help="Read an artifact")
    p_read.add_argument("category", help="Category")
    p_read.add_argument("slug", help="Artifact slug")
    p_read.add_argument("--artifact-type", dest="artifact_type", default=None,
                         help="Artifact type for specs category (solution, technical)")
    _add_scope(p_read)

    # list
    p_list = subparsers.add_parser("list", help="List artifacts")
    p_list.add_argument("--category", default=None, help="Filter by category")
    p_list.add_argument("--tags", default=None, help="Filter by tags (comma-separated)")
    _add_scope(p_list)

    # search
    p_search = subparsers.add_parser("search", help="Full-text search")
    p_search.add_argument("query", help="Search query")
    p_search.add_argument("--category", default=None, help="Filter by category")
    p_search.add_argument("--field", choices=["title", "content", "tags", "all"], default="all",
                          help="Search in specific field")
    _add_scope(p_search)

    # fetch
    p_fetch = subparsers.add_parser("fetch", help="Find artifact by partial slug or title")
    p_fetch.add_argument("partial", help="Partial slug or title to match")
    _add_scope(p_fetch)

    # move
    p_move = subparsers.add_parser("move", help="Move artifact to a different category")
    p_move.add_argument("category", help="Current category")
    p_move.add_argument("slug", help="Artifact slug")
    p_move.add_argument("new_category", help="New category")
    p_move.add_argument("--artifact-type", dest="artifact_type", default=None,
                         help="Artifact type for specs category (solution, technical)")
    _add_scope(p_move)

    # delete
    p_delete = subparsers.add_parser("delete", help="Delete an artifact")
    p_delete.add_argument("category", help="Category")
    p_delete.add_argument("slug", help="Artifact slug")
    p_delete.add_argument("--artifact-type", dest="artifact_type", default=None,
                         help="Artifact type for specs category (solution, technical)")
    _add_scope(p_delete)

    # index
    p_index = subparsers.add_parser("index", help="Show or rebuild the knowledge index")
    _add_scope(p_index)
    p_index.add_argument("--rebuild", action="store_true", help="Rebuild the index from all artifacts")

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        sys.exit(1)

    commands = {
        "init": cmd_init,
        "write": cmd_write,
        "read": cmd_read,
        "list": cmd_list,
        "search": cmd_search,
        "fetch": cmd_fetch,
        "move": cmd_move,
        "delete": cmd_delete,
        "index": cmd_index,
    }

    try:
        commands[args.command](args)
    except Exception as e:
        _error(str(e))


if __name__ == "__main__":
    main()